defaults:
  # images that appear in the art section and so on
  - scope:
      path: "assets/media/img/art"
    values:
      art: true
  - scope:
      path: "assets/media/img/code"
    values:
      code: true
  - scope:
      path: "assets/media/audio"
    values:
      sound: true
  - scope:
      path: "assets/media/img/design"
    values:
      design: true
exclude:
  - "*.less"
  - "README.md"
